/* date = February 24th 2022 9:28 pm */

#ifndef GAME_ASSET_TYPES_H
#define GAME_ASSET_TYPES_H

enum Asset_Tag_Type {
  ASSET_TAG_TYPE_MOOD,
  
  
  ASSET_TAG_TYPE_COUNT,
};

enum Asset_Group_ID {
  ASSET_GROUP_ATLASES,
  
  ASSET_GROUP_BULLET,
  ASSET_GROUP_PLAYER,
  ASSET_GROUP_FONTS,
  
  ASSET_GROUP_COUNT,
};

enum Asset_Type {
  ASSET_TYPE_BITMAP,
  ASSET_TYPE_IMAGE,
  ASSET_TYPE_FONT,
};

#endif //GAME_ASSET_TYPES_H
