// moe_asset_types.h
enum Asset_Tag_Type : U32 {
  ASSET_TAG_TYPE_FONT,

  ASSET_TAG_TYPE_COUNT,
};

enum Asset_Group_Type : U32 {
  ASSET_GROUP_TYPE_BLANK_SPRITE,
  ASSET_GROUP_TYPE_CIRCLE_SPRITE,
  ASSET_GROUP_TYPE_FILLED_CIRCLE_SPRITE,
  ASSET_GROUP_TYPE_ATLAS,
  ASSET_GROUP_TYPE_FONTS,

  ASSET_GROUP_TYPE_COUNT,
};

enum Asset_Type : U32 {
  ASSET_TYPE_SPRITE,
  ASSET_TYPE_FONT,
  ASSET_TYPE_BITMAP,
};
