enum Sprite_ID {
SPRITE_BLANK = PACK_DEFAULT << 16 | 0,
SPRITE_BULLET_CIRCLE = PACK_DEFAULT << 16 | 1,
SPRITE_BULLET_DOT = PACK_DEFAULT << 16 | 2,
SPRITE_PLAYER_BLACK = PACK_DEFAULT << 16 | 3,
SPRITE_PLAYER_WHITE = PACK_DEFAULT << 16 | 4,
}